server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # グローバルAPIへのプロキシ設定
    # ★ https://your-global-api-domain.com の部分を実際のAPIのURL（ドメイン）に変更してください
    location /api/mng/ {
        proxy_pass https://deleuze.lesure.net/api/mng/;
        proxy_ssl_server_name on; # HTTPS通信の場合に必要
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'keep-alive';
        proxy_set_header Host your-global-api-domain.com; # 送信先ホストヘッダー
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /api/mng;
    }
}